CREATE USER SALE_EAST_1 IDENTIFIED BY password; / 
CREATE USER SALE_WEST_1 IDENTIFIED BY password; /
CREATE USER SALE_NORTH_1 IDENTIFIED BY password; /
CREATE USER SALE_SOUTH_1 IDENTIFIED BY password; /



GRANT CONNECT to SALE_EAST_1; /
GRANT CONNECT to SALE_WEST_1; /
GRANT CONNECT to SALE_NORTH_1; /
GRANT CONNECT to SALE_SOUTH_1; /


GRANT ALL PRIVILEGES ON USERS TO SALE_EAST_1; /
GRANT ALL PRIVILEGES ON USERS TO SALE_WEST_1; /
GRANT ALL PRIVILEGES ON USERS TO SALE_NORTH_1; /
GRANT ALL PRIVILEGES ON USERS TO SALE_SOUTH_1; /
