-- as manager
SELECT SA_SESSION.LABEL('PROJECT_OLS_POL') FROM DUAL;

SELECT * FROM INSURANCE.USERS;
SELECT * FROM INSURANCE.MEDICAL_RECORDS;
SELECT * FROM INSURANCE.CAR_RECORDS;
SELECT * FROM INSURANCE.JOURNEY_RECORDS;

-- as SALE_EAST_1
SELECT SA_SESSION.LABEL('PROJECT_OLS_POL') FROM DUAL;

SELECT * FROM INSURANCE.USERS;
SELECT * FROM INSURANCE.MEDICAL_RECORDS;
SELECT * FROM INSURANCE.CAR_RECORDS;
SELECT * FROM INSURANCE.JOURNEY_RECORDS;

-- as HIGH_SALE_EAST
SELECT SA_SESSION.LABEL('PROJECT_OLS_POL') FROM DUAL;

SELECT * FROM INSURANCE.USERS;
SELECT * FROM INSURANCE.MEDICAL_RECORDS;
SELECT * FROM INSURANCE.CAR_RECORDS;
SELECT * FROM INSURANCE.JOURNEY_RECORDS;

-- as ANALYST_WEST_1
SELECT SA_SESSION.LABEL('PROJECT_OLS_POL') FROM DUAL;

SELECT * FROM INSURANCE.USERS;
SELECT * FROM INSURANCE.MEDICAL_RECORDS;
SELECT * FROM INSURANCE.CAR_RECORDS;
SELECT * FROM INSURANCE.JOURNEY_RECORDS;

-- as HIGH_ANALYST_EAST_WEST
SELECT SA_SESSION.LABEL('PROJECT_OLS_POL') FROM DUAL;

SELECT * FROM INSURANCE.USERS;
SELECT * FROM INSURANCE.MEDICAL_RECORDS;
SELECT * FROM INSURANCE.CAR_RECORDS;
SELECT * FROM INSURANCE.JOURNEY_RECORDS;

SELECT USER_ID,
       NAME,
       region,
       is_customer,
       premium,
       LABEL_TO_CHAR(OLS_COL) AS "Label"
FROM INSURANCE.USERS;   