-- as manager
SELECT SA_SESSION.LABEL('PROJECT_OLS_POL') FROM DUAL;

SELECT * FROM INSURANCE.USERS;
SELECT * FROM INSURANCE.MEDICAL_RECORDS;
SELECT * FROM INSURANCE.CAR_RECORDS;
SELECT * FROM INSURANCE.JOURNEY_RECORDS;

-- as 
SELECT SA_SESSION.LABEL('PROJECT_OLS_POL') FROM DUAL;

SELECT * FROM INSURANCE.USERS;
SELECT * FROM INSURANCE.MEDICAL_RECORDS;
SELECT * FROM INSURANCE.CAR_RECORDS;
SELECT * FROM INSURANCE.JOURNEY_RECORDS;

-- as 
SELECT SA_SESSION.LABEL('PROJECT_OLS_POL') FROM DUAL;

SELECT * FROM INSURANCE.USERS;
SELECT * FROM INSURANCE.MEDICAL_RECORDS;
SELECT * FROM INSURANCE.CAR_RECORDS;
SELECT * FROM INSURANCE.JOURNEY_RECORDS;

-- as 
SELECT SA_SESSION.LABEL('PROJECT_OLS_POL') FROM DUAL;

SELECT * FROM INSURANCE.USERS;
SELECT * FROM INSURANCE.MEDICAL_RECORDS;
SELECT * FROM INSURANCE.CAR_RECORDS;
SELECT * FROM INSURANCE.JOURNEY_RECORDS;

-- as 
SELECT SA_SESSION.LABEL('PROJECT_OLS_POL') FROM DUAL;

SELECT * FROM INSURANCE.USERS;
SELECT * FROM INSURANCE.MEDICAL_RECORDS;
SELECT * FROM INSURANCE.CAR_RECORDS;
SELECT * FROM INSURANCE.JOURNEY_RECORDS;

